ALTER TABLE public.mails ADD active BOOLEAN DEFAULT TRUE  NULL;

UPDATE public.mails SET type = 1, body = '<p>%CONTENT%</p><hr id="&lt;hr/&gt;"/><p><b style="font-size: 14px;">© </b>Fresh Start</p>', type_id = null, subject = '', active = true WHERE id = 1;
UPDATE public.mails SET type = 2, body = '<p>Your temporary password is: %PASSWORD% </p>', type_id = null, subject = 'Fresh Start: Password recovery', active = true WHERE id = 2;
UPDATE public.mails SET type = 9, body = '<p>Notice about deleted request:</p><p>From: %DATE_START% to %DATE_END%<br/></p>', type_id = null, subject = 'Fresh Start: Request was deleted', active = true WHERE id = 9;
UPDATE public.mails SET type = 6, body = '<p>Notice: event was removed</p><p></p><p>Date: %SERVICE_DATE%</p><p>Time: %SERVICE_TIME%</p><p>Duration: %SERVICE_DURATION_FULL% ( %SERVICE_DURATION_PREP% + %SERVICE_DURATION_BASE% + %SERVICE_DURATION_CLEAN%)</p><p></p><p><br/></p><p></p>', type_id = null, subject = 'Fresh Start: event was removed', active = true WHERE id = 6;
UPDATE public.mails SET type = 5, body = '<p>Notice about changing your Event:</p><p></p><p></p><p>Service date: %SERVICE_DATE%</p><p>Service duration: %SERVICE_DURATION_FULL% [ %SERVICE_DURATION_PREP% + %SERVICE_DURATION_BASE% + %SERVICE_DURATION_CLEAN% ]</p><p></p><p>Service time: %SERVICE_TIME%</p><p>To confirm changes: %LINK_CONFIRM%</p><p></p>', type_id = null, subject = 'Fresh Start: event was changed', active = true WHERE id = 5;
UPDATE public.mails SET type = 4, body = '<p>Created new Event:</p><p></p><p>Room: %ROOM_NAME%</p><p>Service: %SERVICE_NAME%</p><hr id="&lt;hr/&gt;"/><p></p><p></p><p style="font-size: 14px;">Date: %SERVICE_DATE%</p><p style="font-size: 14px;">Time: %SERVICE_TIME%</p><p style="font-size: 14px;">Duration: %SERVICE_DURATION_FULL% ( %SERVICE_DURATION_PREP% + %SERVICE_DURATION_BASE% + %SERVICE_DURATION_CLEAN%)</p><hr id="&lt;hr/&gt;"/><p></p><p><font color="#333333">To confirm event follow this link: %LINK_CONFIRM%</font></p><p></p><p></p>', type_id = null, subject = 'Fresh Start: created event', active = true WHERE id = 4;
UPDATE public.mails SET type = 7, body = '<p style="font-size: 14px;">Notice about request:</p><p style="font-size: 14px;">From %DATE_START% to %DATE_END%</p><p style="font-size: 14px;">Message:</p><hr id="&lt;hr/&gt;" style="height: 0px;font-size: 14px;"/><p style="font-size: 14px;">%MESSAGE%<br/></p><hr id="&lt;hr/&gt;" style="height: 0px;font-size: 14px;"/><p style="font-size: 14px;">For details follow the link: %LINK%</p>', type_id = null, subject = 'Fresh Start: request for availability', active = true WHERE id = 7;
UPDATE public.mails SET type = 3, body = '<p>Welcome to Fresh Start !</p><p>Your login: %LOGIN%</p><p>Temporary password: %PASSWORD%</p>', type_id = null, subject = 'Fresh Start: Registration', active = true WHERE id = 3;
UPDATE public.mails SET type = 8, body = '<p>Service counts: %SERVICES_COUNT%</p><p>%SERVICES_START%<br/></p><p><b><u>Service</u></b> %SERVICE_NUMBER% of %SERVICES_COUNT%</p><p><b>Room:</b> %ROOM_NAME%</p><p><b>Date:</b> %SERVICE_DATE%</p><p><b>Time: </b>%SERVICE_TIME%</p><p><b>Duration:</b> %SERVICE_DURATION_FULL% ( %SERVICE_DURATION_PREP% +  %SERVICE_DURATION_BASE% + %SERVICE_DURATION_CLEAN%)</p><hr id="&lt;hr/&gt;"/><p>%SERVICES_END%<br/></p>', type_id = null, subject = 'Fresh Start: Events to confirmation', active = true WHERE id = 8;